//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooIds {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZooIds.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abandoned, able, absolute, adorable, adventurous, academic, acceptable, acclaimed, accomplished, accurate, aching, acidic, acrobatic, active, actual, adept, admirable, admired, adolescent, adorable, adored, advanced, afraid, affectionate, aged, aggravating, aggressive, agile, agitated, agonizing, agreeable, ajar, alarmed, alarming, alert, alienated, alive, all, altruistic, amazing, ambitious, ample, amused, amusing, anchored, ancient, angelic, angry, anguished, animated, annual, another, antique, anxious, a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Adjectives {
            get {
                return ResourceManager.GetString("Adjectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aardvark, albatross, alligator, alpaca, ant, anteater, antelope, ape, armadillo, donkey, baboon, badger, barracuda, bat, bear, beaver, bee, bison, boar, buffalo, butterfly, camel, capybara, caribou, cassowary, cat, caterpillar, cattle, chamois, cheetah, chicken, chimpanzee, chinchilla, chough, clam, cobra, cockroach, cod, cormorant, coyote, crab, crane, crocodile, crow, curlew, deer, dinosaur, dog, dogfish, dolphin, dotterel, dove, dragonfly, duck, dugong, dunlin, eagle, echidna, eel, eland, elephant, elk,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Animals {
            get {
                return ResourceManager.GetString("Animals", resourceCulture);
            }
        }
    }
}
